# Generated by Django 3.1.7 on 2021-05-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location1', models.CharField(max_length=100)),
                ('location2', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='cab/images')),
                ('luggagebag', models.IntegerField()),
                ('seat', models.IntegerField()),
                ('price', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
